steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "europe-west8-docker.pkg.dev/pascal2024/projectworkapi/projectworkapi:${SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west8-docker.pkg.dev/pascal2024/projectworkapi/projectworkapi:${SHORT_SHA}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "projectworkapi",
        "--image",
        "europe-west8-docker.pkg.dev/pascal2024/projectworkapi/projectworkapi:${SHORT_SHA}",
        "--region",
        "europe-west8",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
options:
  logging: CLOUD_LOGGING_ONLY