DROP DATABASE IF EXISTS Pascal2024;
CREATE DATABASE Pascal2024;

USE Pascal2024;


CREATE TABLE Categories(
	Id INT PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Image VARCHAR(255)
);

CREATE TABLE Products(
	Id INT PRIMARY KEY auto_increment,
	Title  VARCHAR(100) NOT NULL,
	Description VARCHAR(1024) NOT NULL,
	Price FLOAT NOT NULL,
	Stars FLOAT NOT NULL,
	Images VARCHAR(1024) NOT NULL,
	IdCategory INT NOT NULL,
	FOREIGN KEY(IdCategory) REFERENCES Categories(Id)
);

CREATE TABLE Orders(
	Id INT PRIMARY KEY auto_increment,
	CreateDate DATETIME NOT NULL,
	ClientName VARCHAR(255) NOT NULL,
	Address VARCHAR(1024) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	TotalPrice FLOAT NOT NULL
);

CREATE TABLE OrderDetail(
	Id INT PRIMARY KEY auto_increment,
	IdOrder INT NOT NULL,
	IdProduct INT NOT NULL,
	Quantity INT NOT NULL CHECK (Quantity > 0),
	FOREIGN KEY(IdOrder) REFERENCES Orders(Id),
	FOREIGN KEY(IdProduct) REFERENCES Products(Id)
);


INSERT INTO Categories (Id, Name, Image) VALUES
(1, 'Abbigliamento', 'QkIa5tT.jpeg'),
(2, 'Elettronica', 'ZANVnHE.jpeg'),
(3, 'Mobili', 'Qphac99.jpeg'),
(4, 'Scarpe', 'qNOjJje.jpeg'),
(5, 'Varie', 'BG8J0Fj.jpg');

INSERT INTO Products (Title, Description, Price, Stars, Images, IdCategory) VALUES
('T-Shirt Grafica Montagna Maestosa', 'Eleva il tuo guardaroba con questa elegante t-shirt nera caratterizzata da una sorprendente grafica monocromatica di una catena montuosa. Perfetta per chi ama la natura o desidera aggiungere un tocco di design ispirato alla natura al proprio look, questa maglietta è realizzata in tessuto morbido e traspirante che garantisce comfort per tutto il giorno. Ideale per uscite casual o come regalo unico, questa t-shirt è un''aggiunta versatile a qualsiasi collezione.', 44, 4.5, 'QkIa5tT.jpeg;jb5Yu0h.jpeg;UlxxXyG.jpeg', 1),
('Felpa con Cappuccio Classica Rossa', 'Eleva il tuo guardaroba casual con la nostra Felpa con Cappuccio Classica Rossa. Realizzata con una morbida miscela di cotone per un comfort ottimale, questa vivace felpa rossa presenta una tasca a marsupio, cappuccio regolabile con coulisse e polsini a costine per una vestibilità aderente. Il design senza tempo garantisce un facile abbinamento con jeans o joggers per un look rilassato ma elegante, rendendola un''aggiunta versatile al tuo abbigliamento quotidiano.', 10, 4.0, '1twoaDy.jpeg;FDwQgLy.jpeg;kg1ZhhH.jpeg', 1),
('Felpa con Cappuccio Grigia Classica', 'Rimani comodo e alla moda con la nostra Felpa con Cappuccio Grigia Classica. Realizzata in tessuto morbido e resistente, presenta una tasca a marsupio, cappuccio regolabile con coulisse e polsini a costine. Perfetta per una giornata casual fuori o una serata rilassante a casa, questa felpa è un''aggiunta versatile a qualsiasi guardaroba.', 69, 4.0, 'cHddUCu.jpeg;CFOjAgK.jpeg;wbIMMme.jpeg', 1),
('Felpa con Cappuccio Grigia Classica', 'Eleva il tuo abbigliamento casual con la nostra Felpa con Cappuccio Grigia Classica. Realizzata in morbido misto cotone, questa felpa presenta una tasca a marsupio frontale, un cappuccio regolabile con coulisse e polsini a costine per una vestibilità aderente. Perfetta per le serate fredde o i fine settimana pigri, si abbina perfettamente ai tuoi jeans o joggers preferiti.', 90, 3.5, 'R2PN9Wq.jpeg;IvxMPFr.jpeg;7eW9nXP.jpeg', 1),
('Felpa con Cappuccio Nera Classica', 'Eleva il tuo guardaroba casual con la nostra Felpa con Cappuccio Nera Classica. Realizzata in tessuto morbido di alta qualità che garantisce comfort e durata, questa felpa presenta una spaziosa tasca a marsupio e un cappuccio regolabile con coulisse. Il suo design versatile la rende perfetta per una giornata rilassata a casa o una uscita casual.', 79, 4.5, 'cSytoSD.jpeg;WwKucXb.jpeg;cE2Dxh9.jpeg', 1),
('Joggers a Vestibilità Comoda Classici', 'Scopri il perfetto connubio tra stile e comfort con i nostri Joggers a Vestibilità Comoda Classici. Questi versatili joggers neri presentano una morbida fascia elastica in vita con coulisse regolabile, due tasche laterali e polsini alle caviglie a costine per una vestibilità sicura. Realizzati in tessuto leggero e resistente, sono ideali sia per giornate attive che per momenti di relax.', 25, 3.0, 'ZKGofuB.jpeg;GJi73H0.jpeg;633Fqrz.jpeg', 1),
('Joggers a Coulisse a Vestibilità Comoda Classici', 'Vivi il perfetto connubio tra comfort e stile con i nostri Joggers a Coulisse a Vestibilità Comoda Classici. Progettati per una vestibilità rilassata, questi joggers presentano un tessuto morbido e elasticizzato, comode tasche laterali e una vita con coulisse regolabile con eleganti dettagli dorati. Ideali per rilassarsi o sbrigare commissioni, questi pantaloni diventeranno rapidamente il tuo capo preferito per un abbigliamento casual senza sforzo.', 79, 3.5, 'mp3rUty.jpeg;JQRGIc2.jpeg', 1),
('Pantaloni da Jogging Rossi Classici', 'Vivi il massimo del comfort con i nostri pantaloni da jogging rossi, perfetti sia per le sessioni di allenamento che per rilassarsi in casa. Realizzati in tessuto morbido e resistente, questi joggers presentano una vita aderente, una coulisse regolabile e pratiche tasche laterali per la funzionalità. Il loro design affusolato e i polsini elastici offrono una vestibilità moderna che ti mantiene elegante in movimento.', 98, 4.0, '9LFjwpI.jpeg;vzrTgUR.jpeg;p5NdI6n.jpeg', 1),
('Berretto da Baseball Blu Navy Classico', 'Esci con stile con questo elegante berretto da baseball blu navy. Realizzato in materiale resistente, presenta un design liscio e strutturato e una cinghia regolabile per una vestibilità perfetta. Proteggi i tuoi occhi dal sole e completa i tuoi look casual con questo accessorio versatile e senza tempo.', 61, 2.5, 'R3iobJA.jpeg;Wv2KTsf.jpeg;76HAxcA.jpeg', 1),
('Berretto da Baseball Blu Classico', 'Completa il tuo look casual con il nostro Berretto da Baseball Blu Classico, realizzato con materiali di alta qualità per un comfort duraturo. Caratterizzato da un design senza tempo a sei pannelli con visiera precurvata, questo cappello regolabile offre sia stile che praticità per l''uso quotidiano.', 86, 5.0, 'wXuQ7bm.jpeg;BZrIEmb.jpeg;KcT6BE0.jpeg', 1),
('Berretto da Baseball Rosso Classico', 'Eleva il tuo guardaroba casual con questo intramontabile berretto da baseball rosso. Realizzato in tessuto resistente, presenta una vestibilità confortevole con una cinghia regolabile sul retro, assicurando una taglia unica per tutti. Perfetto per le giornate di sole o per aggiungere un tocco sportivo al tuo outfit.', 35, 3.0, 'cBuLvBi.jpeg;N1GkCIR.jpeg;kKc9A5p.jpeg', 1),
('Shorts Chino Verde Oliva Classici', 'Eleva il tuo guardaroba casual con questi shorts chino verde oliva classici. Progettati per comfort e versatilità, presentano una cintura liscia, tasche pratiche e una vestibilità su misura che li rende perfetti sia per i fine settimana rilassati che per le occasioni smart-casual. Il tessuto resistente garantisce che resistano alle attività quotidiane mantenendo uno stile elegante.', 84, 4.0, 'UsFIvYs.jpeg;YIq57b6.jpeg', 1),
('Shorts Sportivi a Vita Alta Classici', 'Resta comodo e alla moda con i nostri Shorts Sportivi a Vita Alta Classici. Progettati per movimenti ottimali e versatilità, questi shorts sono un must-have per il tuo guardaroba da allenamento. Caratterizzati da una vita alta che valorizza la figura, tessuto traspirante e una vestibilità sicura che garantisce che restino al loro posto durante qualsiasi attività, questi shorts sono perfetti per la palestra, la corsa o anche solo per un look casual.', 43, 4.5, 'eGOUveI.jpeg;UcsGO7E.jpeg;NLn4e7S.jpeg', 1),
('T-Shirt Classica a Girocollo Bianca', 'Eleva i tuoi capi essenziali con questa versatile t-shirt bianca a girocollo. Realizzata in morbido e traspirante cotone misto, offre comfort e durata. Il suo design elegante e senza tempo assicura che si abbini bene a praticamente qualsiasi outfit. Ideale per essere indossata da sola o stratificata, questa t-shirt è un capo indispensabile per qualsiasi guardaroba.', 39, 3.5, 'axsyGpD.jpeg;T8oq9X2.jpeg;J6MinJn.jpeg', 1),
('T-Shirt Bianca Classica - Stile e Comfort Senza Tempo', 'Eleva il tuo guardaroba quotidiano con la nostra T-Shirt Bianca Classica. Realizzata in pregiato cotone morbido, questa versatile t-shirt combina comfort e durata, perfetta per l''uso quotidiano. Caratterizzata da una vestibilità rilassata e unisex che valorizza ogni tipo di corporatura, è un capo essenziale per qualsiasi ensemble casual. Facile da curare e lavabile in lavatrice, questa t-shirt bianca mantiene la sua forma e morbidezza lavaggio dopo lavaggio. Abbinala ai tuoi jeans preferiti o indossala sotto una giacca per un look elegante.', 73, 5.0, 'Y54Bt8J.jpeg;SZPDSgy.jpeg;sJv4Xx0.jpeg', 1),
('T-Shirt Nera Classica', 'Eleva il tuo stile quotidiano con la nostra T-Shirt Nera Classica. Questo capo essenziale è realizzato in morbido e traspirante cotone per un comfort che dura tutto il giorno. Il suo design versatile presenta un classico girocollo e maniche corte, rendendola perfetta da indossare da sola o stratificata. Resistente e facile da curare, diventerà sicuramente uno dei tuoi preferiti nel guardaroba.', 35, 4.0, '9DqEOV5.jpeg;ae0AEYn.jpeg;mZ4rUjj.jpeg', 1),
('Controller da Gioco Wireless Bianco e Arancione', 'Eleva la tua esperienza di gioco con questo controller wireless all''avanguardia, caratterizzato da una base bianca e dettagli arancioni vibranti. Progettato per un gioco preciso, la forma ergonomica e i pulsanti reattivi offrono il massimo comfort e controllo per ore di gioco ininterrotto. Compatibile con molteplici piattaforme di gioco, questo controller è un must-have per ogni giocatore serio che desidera migliorare il proprio setup.', 69, 4.0, 'ZANVnHE.jpeg;Ro5z6Tn.jpeg;woA93Li.jpeg', 2),
('Set di Cuffie Wireless e Auricolari In-Ear', 'Vivi la fusione di stile e suono con questo sofisticato set audio che include un paio di eleganti cuffie wireless bianche con qualità sonora cristallina e comfort over-ear. Il set include anche un paio di auricolari durevoli, perfetti per uno stile di vita dinamico. Eleva il tuo piacere musicale con questo duo versatile, progettato per soddisfare tutte le tue esigenze di ascolto.', 44, 3.5, 'yVeIeDa.jpeg;jByJ4ih.jpeg;KXj6Tpb.jpeg', 2),
('Cuffie Over-Ear Comode ed Eleganti', 'Vivi un''esperienza sonora superiore con le nostre Cuffie Over-Ear Comode ed Eleganti, progettate per un uso prolungato con cuscinetti auricolari imbottiti e un''archetto regolabile e imbottito. Ideali per un ascolto immersivo, sia a casa, in ufficio che in movimento. La loro costruzione durevole e il design senza tempo offrono un aspetto esteticamente gradevole e prestazioni durature.', 28, 4.5, 'SolkFEB.jpeg;KIGW49u.jpeg;mWwek7p.jpeg', 2),
('Tostapane Efficiente a 2 Fette', 'Rendi più piacevole la tua routine mattutina con il nostro tostapane elegante a 2 fette, dotato di controlli di doratura regolabili e un vassoio raccogli-briciole rimovibile per una facile pulizia. Questo elettrodomestico compatto e elegante è perfetto per qualsiasi cucina, garantendo che il tuo toast sia sempre dorato e delizioso.', 48, 3.5, 'keVCVIa.jpeg;afHY7v2.jpeg;yAOihUe.jpeg', 2),
('Mouse Wireless Elegante', 'Sperimenta una navigazione fluida e precisa con questo moderno mouse wireless, caratterizzato da una finitura lucida e un design ergonomico e confortevole. Il suo tracciamento reattivo e l''interfaccia facile da usare lo rendono l''accessorio perfetto per qualsiasi configurazione di desktop o laptop. La tonalità blu elegante aggiunge un tocco di colore al tuo spazio di lavoro, mentre le sue dimensioni compatte assicurano che si adatti perfettamente alla tua borsa per la produttività in movimento.', 10, 2.0, 'w3Y8NwQ.jpeg;WJFOGIC.jpeg;dV4Nklf.jpeg', 2),
('Laptop Moderno con Illuminazione Ambientale', 'Sperimenta un livello di informatica superiore con il nostro laptop ultra-sottile, dotato di un display sorprendente illuminato da luci ambientali. Questa macchina ad alte prestazioni è perfetta sia per il lavoro che per il gioco, offrendo una potente elaborazione in un design elegante e portatile. I colori vivaci aggiungono un tocco di personalità alla tua collezione di tecnologia, rendendolo tanto stiloso quanto funzionale.', 43, 3.0, 'OKn1KFI.jpeg;G4f21Ai.jpeg;Z9oKRVJ.jpeg', 2),
('Laptop Moderno per Professionisti', 'Sperimenta la tecnologia all''avanguardia e il design elegante con il nostro ultimo modello di laptop. Perfetto per professionisti in movimento, questo laptop ad alte prestazioni vanta un potente processore, ampio spazio di archiviazione e una batteria di lunga durata, il tutto racchiuso in un telaio leggero e sottile per la massima portabilità. Acquista ora per elevare il tuo lavoro e il tuo svago.', 97, 4.5, 'ItHcq7o.jpeg;55GM3XZ.jpeg;tcNJxoW.jpeg', 2),
('Cuffie Over-Ear Rosse e Argento Eleganti', 'Immergiti in una qualità del suono superiore con queste eleganti cuffie over-ear rosse e argento. Progettate per comfort e stile, le cuffie presentano cuscinetti auricolari imbottiti, un''archetto regolabile e imbottito e un cavo rosso staccabile per una facile conservazione e portabilità. Perfette per gli amanti della musica e gli audiofili che apprezzano sia l''aspetto che la fedeltà audio.', 39, 4.0, 'YaSqa06.jpeg;isQAliJ.jpeg;5B8UQfh.jpeg', 2),
('Cover per Telefono con Finitura a Specchio', 'Eleva l''aspetto del tuo smartphone con questa cover per telefono ultra-elegante con finitura a specchio. Progettata per offrire stile e protezione, la cover presenta una superficie riflettente che aggiunge un tocco di eleganza mantenendo il tuo dispositivo al sicuro da graffi e urti. Perfetta per chi ama un''estetica minimalista e moderna.', 27, 4.5, 'yb9UQKL.jpeg;m2owtQG.jpeg;bNiORct.jpeg', 2),
('Smartwatch Elegante con Display Vivido', 'Sperimenta la modernità con il nostro smartwatch high-tech, caratterizzato da un vivace display touch screen, quadranti personalizzabili e un comodo cinturino in silicone blu. Questo smartwatch ti tiene connesso con notifiche e tracciamento del fitness, mentre mostra uno stile eccezionale e versatilità.', 16, 3.5, 'LGk9Jn2.jpeg;1ttYWaI.jpeg;sPRWnJH.jpeg', 2),
('Divano in Pelle Moderno ed Elegante', 'Eleva l''eleganza del tuo spazio abitativo con il nostro divano in pelle moderno ed elegante. Progettato con un''estetica minimalista, presenta linee pulite e una finitura in pelle lussuosa. Le robuste gambe in metallo offrono stabilità e supporto, mentre i cuscini imbottiti garantiscono comfort. Perfetto per case contemporanee o sale d''attesa, questo divano è un pezzo d''arredamento che combina stile e praticità.', 53, 2.5, 'Qphac99.jpeg;dJjpEgG.jpeg;MxJyADq.jpeg', 3),
('Tavolo da Pranzo Moderno in Legno Massello', 'Eleva il tuo spazio da pranzo con questo elegante tavolo da pranzo moderno in legno massello, caratterizzato da una finitura in noce e gambe affusolate per un''estetica senza tempo. La sua robusta costruzione in legno e il design minimalista lo rendono un pezzo versatile che si adatta a una varietà di stili di arredamento. Perfetto per cene intime o come punto di appoggio per il caffè mattutino.', 24, 3.0, 'DMQHGA0.jpeg;qrs9QBg.jpeg;XVp8T1I.jpeg', 3),
('Tavolo da Pranzo con Base Dorata e Piano in Pietra', 'Eleva il tuo spazio da pranzo con questo lussuoso tavolo, caratterizzato da una robusta base in metallo dorato con un design a barre intricate che offre sia stabilità che eleganza chic. Il piano liscio in pietra di forma rotonda offre una superficie robusta per il tuo piacere culinario. Perfetto sia per i pasti quotidiani che per le occasioni speciali, questo tavolo si abbina facilmente a qualsiasi arredamento moderno o glam.', 66, 4.0, 'NWIJKUj.jpeg;Jn1YSLk.jpeg;VNZRvx5.jpeg', 3),
('Poltrona Moderna in Teal', 'Eleva il tuo spazio abitativo con questa poltrona splendidamente realizzata, caratterizzata da una struttura in legno elegante che si abbina alla vivace tappezzeria teal. Ideale per aggiungere un tocco di colore e stile contemporaneo a qualsiasi stanza, questa poltrona offre sia comfort eccezionale che design sofisticato. Perfetta per leggere, rilassarsi o creare un accogliente angolo conversazione.', 25, 4.5, '6wkyyIN.jpeg;Ald3Rec.jpeg;dIqo03c.jpeg', 3),
('Tavolo da Pranzo Elegante in Legno Massello', 'Migliora il tuo spazio da pranzo con questo tavolo da pranzo contemporaneo in legno massello, caratterizzato da una finitura calda. La sua robusta costruzione e il design minimalista lo rendono un''aggiunta perfetta per qualsiasi casa che cerca un tocco di eleganza. Può ospitare comodamente fino a sei ospiti e include un centrotavola a ciotola di frutta. L''illuminazione a sospensione non è inclusa.', 67, 3.5, '4lTaHfF.jpeg;JktHE1C.jpeg;cQeXQMi.jpeg', 3),
('Postazione di Lavoro Minimalista Moderna', 'Eleva il tuo ufficio domestico con la nostra postazione di lavoro minimalista moderna, caratterizzata da una scrivania in legno elegante sormontata da un computer elegante, una lampada da scrivania regolabile in legno e accessori complementari per uno spazio di lavoro pulito e produttivo. Questa postazione è perfetta per i professionisti che cercano un look contemporaneo che combini funzionalità e design.', 49, 4.5, '3oXNBst.jpeg;ErYYZnT.jpeg;boBPwYW.jpeg', 3),
('Sedia da Ufficio Ergonomica Moderna', 'Eleva il tuo spazio ufficio con questa elegante e confortevole sedia da ufficio ergonomica moderna. Progettata per fornire un supporto ottimale durante tutta la giornata lavorativa, presenta un meccanismo di altezza regolabile, ruote scorrevoli per una facile mobilità e un sedile imbottito per un comfort prolungato. Le linee pulite e il design minimalista bianco la rendono un''aggiunta versatile a qualsiasi spazio di lavoro contemporaneo.', 71, 4.0, '3dU0m72.jpeg;zPU3EVa.jpeg', 3),
('Scarpe da Calcio Olografiche Futuristiche', 'Scendi in campo e distingueti dalla massa con queste scarpe da calcio olografiche che catturano l''attenzione. Progettate per il giocatore moderno, queste scarpe presentano una silhouette elegante, una costruzione leggera per la massima agilità e tacchetti durevoli per una trazione ottimale. La finitura olografica riflette un arcobaleno di colori mentre ti muovi, garantendo che sarai notato sia per le tue abilità che per il tuo stile. Perfette per l''atleta attento alla moda che vuole fare una dichiarazione.', 39, 3.5, 'qNOjJje.jpeg;NjfCFnu.jpeg;eYtvXS1.jpeg', 4),
('Tacchi Alti Glitterati Arcobaleno', 'Mettiti sotto i riflettori con questi accattivanti tacchi alti glitterati arcobaleno. Progettati per stupire, ogni scarpa vanta un caleidoscopio di colori scintillanti che catturano e riflettono la luce ad ogni passo. Perfetti per occasioni speciali o una serata fuori, questi stili sono sicuri di attirare l''attenzione e elevare qualsiasi ensemble.', 39, 4.5, '62gGzeF.jpeg;5MoPuFM.jpeg;sUVj7pK.jpeg', 4),
('Sandali Espadrillas in Denim per l''Estate', 'Entra nell''estate con stile con i nostri sandali espadrillas in denim. Caratterizzati da una suola intrecciata in juta per un tocco classico e cinturini in denim regolabili per una vestibilità aderente, questi sandali offrono sia comfort che un tocco di moda. Il design facile da indossare li rende comodi per giornate in spiaggia o uscite casual.', 33, 4.0, '9qrmE1b.jpeg;wqKxBVH.jpeg;sWSV6DK.jpeg', 4),
('Sneakers Vivaci Arancioni e Blu', 'Entra con stile con queste sneakers accattivanti caratterizzate da una combinazione di colori arancione e blu. Progettate per comfort e moda, queste scarpe sono dotate di suole flessibili e plantari imbottiti, perfette per individui attivi che non vogliono compromettere lo stile. Gli accenti argentati riflettenti aggiungono un tocco di modernità, rendendole un accessorio distintivo per il tuo allenamento o abbigliamento casual.', 27, 3.0, 'hKcMNJs.jpeg;NYToymX.jpeg;HiiapCt.jpeg', 4),
('Sneakers Classiche Rosa Vivaci', 'Entra con stile con le nostre Sneakers Classiche Rosa Vivaci! Queste scarpe accattivanti presentano una vivace tonalità rosa con dettagli bianchi iconici, offrendo un design elegante e senza tempo. Costruite con materiali durevoli e una vestibilità comoda, sono perfette per chi cerca un tocco di colore nel proprio abbigliamento quotidiano. Prendi un paio oggi stesso e aggiungi un po'' di vivacità al tuo passo!', 84, 5.0, 'mcW42Gi.jpeg;mhn7qsF.jpeg;F8vhnFJ.jpeg', 4),
('Sneaker Futuristica Alta Argento e Oro', 'Entra nel futuro con questa sneaker alta che cattura l''attenzione, progettata per chi osa distinguersi. La sneaker presenta un corpo argento lucido con accenti dorati, offrendo una svolta moderna alle calzature classiche. Il design alto offre supporto e stile, rendendola l''aggiunta perfetta a qualsiasi collezione di moda all''avanguardia. Prendi un paio oggi stesso e eleva il tuo gioco di scarpe!', 68, 4.5, 'npLfCGq.jpeg;vYim3gj.jpeg;HxuHwBO.jpeg', 4),
('Stivali Alti Chic Futuristici', 'Eleva il tuo stile con i nostri stivali alti chic futuristici che uniscono un design audace a un''estetica all''avanguardia. Questi stivali presentano un tacco color block unico, una silhouette elegante e una finitura grigia versatile che si abbina facilmente a qualsiasi outfit all''avanguardia. Progettati per l''individuo attento alla moda, questi stivali sono sicuri di fare una dichiarazione.', 36, 3.0, 'HqYqLnW.jpeg;RlDGnZw.jpeg;qa0O6fg.jpeg', 4),
('Decolleté con Tacco Oro in Vernice', 'Entra nella sofisticazione con queste chic decolleté in vernice, che mostrano una finitura lucida e un accattivante tacco a blocco dorato. Il dettaglio della fibbia ornata aggiunge un tocco di glamour, perfetto per elevare il tuo abbigliamento da sera o completare un look da giorno elegante.', 53, 4.0, 'AzAY4Ed.jpeg;umfnS9P.jpeg;uFyuvLg.jpeg', 4),
('Mocassini in Pelle Viola Eleganti', 'Entra nella sofisticazione con i nostri mocassini in pelle viola eleganti, perfetti per fare una dichiarazione audace. Realizzati in pelle di alta qualità con una finitura viola vibrante, queste scarpe presentano una silhouette classica da mocassino aggiornata con un tocco contemporaneo. Il design slip-on comodo e le suole durevoli garantiscono sia stile che funzionalità per l''uomo moderno.', 17, 3.5, 'Au8J9sX.jpeg;gdr8BW2.jpeg;KDCZxnJ.jpeg', 4),
('Scarpe Casual Blu Scamosciate', 'Entra nel comfort con le nostre Scarpe Casual Blu Scamosciate, perfette per l''uso quotidiano. Queste scarpe presentano una tomaia in elegante camoscio blu, suole in gomma durevole per una trazione superiore e lacci classici per una vestibilità aderente. Il design elegante si abbina bene sia con jeans che con chinos, rendendole un''aggiunta versatile a qualsiasi guardaroba.', 39, 4.5, 'sC0ztOB.jpeg;Jf9DL9R.jpeg;R1IN95T.jpeg', 4),
('Bicicletta Elettrica Futuristica', 'Questa moderna bicicletta elettrica combina stile ed efficienza con il suo design unico e caratteristiche di prestazioni di alto livello. Dotata di un telaio durevole, una batteria migliorata e capacità tecnologiche integrate, è perfetta per il pendolare ecologico che desidera navigare in città con facilità.', 22, 4.0, 'BG8J0Fj.jpg;ujHBpCX.jpg;WHeVL9H.jpg', 5),
('Go-Kart All-Terrain Elegante', 'Prova l''emozione delle avventure all''aperto con il nostro Go-Kart All-Terrain elegante, dotato di un telaio durevole, un sedile da corsa comodo e pneumatici robusti e a grande battistrada perfetti per affrontare una varietà di terreni. Progettato per chi cerca il divertimento di tutte le età, questo go-kart è una scelta ideale per corse in cortile o per esplorare i sentieri locali.', 37, 3.0, 'Ex5x3IU.jpg;z7wAQwe.jpg;kc0Dj9S.jpg', 5),
('Eau de Parfum Agrumato Radiante', 'Indulgi nell''essenza dell''estate con questa vibrante Eau de Parfum agrumata. Racchiusa in una bottiglia di vetro elegante con un tappo arancione audace, questa fragranza incarna freschezza ed eleganza. Perfetta per l''uso quotidiano, è una delizia olfattiva che lascia un''impressione duratura e frizzante.', 73, 4.5, 'xPDwUb3.jpg;3rfp691.jpg;kG05a29.jpg', 5),
('Valigia Rigida Verde Oliva', 'Viaggia con stile con il nostro robusto bagaglio a mano rigido, perfetto per weekend fuori porta e viaggi di lavoro. Questa elegante valigia verde oliva presenta ruote scorrevoli per una facile navigazione in aeroporto, una robusta maniglia telescopica e un compartimento con cerniera sicura per mantenere i tuoi effetti personali al sicuro. Le sue dimensioni compatte soddisfano la maggior parte dei requisiti per i compartimenti superiori delle compagnie aeree, garantendo un''esperienza di volo senza problemi.', 48, 4.0, 'jVfoZnP.jpg;Tnl15XK.jpg;7OqTPO6.jpg', 5),
('Borsa alla Moda Trasparente', 'Eleva il tuo stile con la nostra borsa alla moda trasparente, perfetta per mostrare i tuoi oggetti essenziali con un tocco moderno. Questo accessorio trendy è caratterizzato da una costruzione acrilica durevole, hardware di lusso dorato e una cinghia a catena elegante. Le sue dimensioni compatte assicurano che tu possa portare con te i tuoi articoli quotidiani con facilità e raffinatezza.', 61, 3.5, 'Lqaqz59.jpg;uSqWK0m.jpg;atWACf1.jpg', 5),
('Occhiali da Sole con Lenti Rosa', 'Migliora il tuo gioco di stile con questi occhiali da sole alla moda con montatura nera e lenti rosa. Perfetti per fare una dichiarazione mentre proteggono i tuoi occhi dall''abbagliamento. Il loro colore audace e il design contemporaneo rendono questi occhiali un accessorio indispensabile per chi ama aggiungere un tocco di colore al proprio ensemble.', 38, 3.0, '0qQBkxX.jpg;I5g1DoE.jpg;myfFQBW.jpg', 5),
('Set di Bicchieri in Vetro Eleganti', 'Migliora la tua collezione di bicchieri con il nostro sofisticato set di bicchieri in vetro, perfetti per servire le tue bevande preferite. Questo set versatile include bicchieri sia trasparenti che leggermente colorati, conferendo un tocco moderno a qualsiasi tavola. Realizzati con materiali di qualità, questi bicchieri durevoli sono progettati per resistere all''uso quotidiano mantenendo il loro fascino elegante.', 50, 4.0, 'TF0pXdL.jpg;BLDByXP.jpg;b7trwCv.jpg', 5);
